# Generated by Django 2.0.6 on 2019-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messervice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tuitionservice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
